#!/bin/sh

# Function to validate URL format
is_valid_url() {
  echo "$1" | grep -E -q '^https?://[a-zA-Z0-9.-]+(:[0-9]+)?(/.*)?$'
}

# Function to send a webhook call
send_webhook() {
  url="$1"
  status="$2"
  extra_args="$3"

  # Skip if URL is empty
  [ -z "$url" ] && return 0

  if is_valid_url "$url"; then
    HOSTNAME=$(hostname 2>/dev/null || echo "unknown")
    TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    echo "Executing webhook call to ${url} with status ${status}"
    # shellcheck disable=SC2086
    curl --fail --silent --request POST \
      --url "$url" \
      --header 'Content-Type: application/json' \
      --data "{\"status\": \"${status}\", \"hostname\": \"${HOSTNAME}\", \"timestamp\": \"${TIMESTAMP}\", \"database\": \"${POSTGRES_DB}\", \"project\": \"${PROJECT_NAME}\"}" \
      --max-time 10 \
      --retry 5 \
      $extra_args > /dev/null || echo "⚠️ Webhook call to ${url} failed." >&2
  else
    echo "⚠️ Invalid webhook URL: ${url}" >&2
  fi
}

# Action passed as an argument
ACTION="$1"

case "$ACTION" in
  "error")
    send_webhook "$WEBHOOK_URL" "error" "$WEBHOOK_EXTRA_ARGS"
    send_webhook "$WEBHOOK_ERROR_URL" "error" "$WEBHOOK_EXTRA_ARGS"
  ;;

  "pre-backup")
    send_webhook "$WEBHOOK_PRE_BACKUP_URL" "pre-backup" "$WEBHOOK_EXTRA_ARGS"
  ;;

  "post-backup")
    send_webhook "$WEBHOOK_URL" "post-backup" "$WEBHOOK_EXTRA_ARGS"
    send_webhook "$WEBHOOK_POST_BACKUP_URL" "post-backup" "$WEBHOOK_EXTRA_ARGS"
  ;;
esac
